config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'question#home'
  get "ask", to: "questions#ask", as: :ask
  get "answer", to: "questions#answer", as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def ask
    end

    def answer
        if params[:question].downcase == "i am going to work"
            @answer = "Great!"
          elsif params[:question].end_with?("?")
            @answer = "Silly question, get dressed and go to work!"
          else
            @answer = "I don't care, get dressed and go to work!"
          end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="container">
    <h1>Stupid Coaching</h1>

    <div>
        <h2><%= params[:question] %></h2>
        <p>- You</p>
    </div>

    <div>
        <h2><%= @answer %></h2>
        <p>- Your Coach</p>
    </div>
    
    <%= link_to "ask another question", ask_path %>
</div>


app/views/questions/ask.html.erb
<div class="container">
    <h1>Stupid Coaching</h1>

    <form action="/answer" method="get">
        <input type="text" name="question" value="<%= params[:question] %>" placeholder="What do you want ?">
        <input type="submit" value="Ask!">
    </form>
</div>


